name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build .
      - run: quadratic-equation/test-solve
      - run: commands/move/test-move
      - run: commands/rotate/test-rotate
      - run: commands/handler/test-handler
      - run: commands/test-commands
      - run: commands/fuel-commands/test-fuel-commands
      - run: commands/adapters/test-change-velocity
