name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build .
      - run: quadratic-equation/test-solve
      - run: move/test-move
      - run: commands/test-handler
      - run: commands/test-commands
